# mysql

# default: &default
#   adapter: postgresql
#   encoding: utf8mb4
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   username: root
#   password:
#   socket: /tmp/mysql.sock

# development:
#   <<: *default
#   database: sidekick_sneaker_development

# test:
#   <<: *default
#   database: sidekick_sneaker_test

# production:
#   <<: *default
#   database: sidekick_sneaker_production
#   username: sidekick_sneaker
#   password: <%= ENV['SIDEKICK_SNEAKER_DATABASE_PASSWORD'] %>

# postgresql

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username:
  password:
  template: template0

development:
  <<: *default
  database: sidekick_sneaker_development

test:
  <<: *default
  database: sidekick_sneaker_test

production:
  <<: *default
  database: sidekick_sneaker_production
  username: sidekick_sneaker
  password: <%= ENV['appname_DATABASE_PASSWORD'] %>